{% set name = "dash-core-components" %}
{% set filename = "dash_core_components" %}
{% set version = "0.37.0" %}
{% set sha256 = "c56aa1768bce168f98734303ac330808051fed9ccf44341e4a83adae3c229bd1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ filename }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ filename }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - dash  # not listed in the setup.py

test:
  imports:
    - dash_core_components
    - dash_core_components.version

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash-core-components
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Dash UI core component suite'

extra:
  recipe-maintainers:
    - moorepants
