travis:
  secure:
    BINSTAR_TOKEN: ZTmSKErzPxud/l7B/uUPI1j84vCMT6JE+O4ryuZ7hHiSIPVcN1hFO7T8lOvd9WEYHvGT+mr4UTzrkMu6fqZa9VtzuInSl7l2NT8eybREeIgBd2aHeiFCYHJ5kHavfnUXOley6l5k+HfHyJmMqKbeMo7lYSqXeo9YpEIe5bYnIVlIirvQQNDRXtCFen1gWJwvVWHu6iMMpzz7Q45aZDt5PuZI92HzR/UMLbd0YnE9yXyhNY5357yXPZoNddTcULjcjbNCo4Ug0pUjkCTLq0lzQFxXHNMdxmWJVaCGlbyR8sODpR3guY0AXXmv0NXhXOE3OXcQBzEPbmiNdBMJbnOZY4Ywlylm5YnNi34Tnovr4pBp7BBB+leksjruyluo58QyrZmNbf46z41SwzMkiMUhqU/qtOyEMndy+HgWw7PSvbsHw4TDMmEuE1GDHx5tSXB3oNE5B/q38WX3V3parKK2CoXE6+EfNQLxQlVYn3u4hmhDZKR8fhyQBbpw4EBEHNntdjSQvHenKrfCcdZ84oIDGwUe7PE7KFPI7njSfGxqA20vKZxbnU8Xd+7ab9aOiigDVGu2oFw9uavczDhhHGQ69jXcbXDgSXirLftCB77Fwo0KNwNKM/v3WkG/TqcVWGdxh/k7RzRop9r6ia3y0n0u+QS5wIDH0N2coWo92ukt3R4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
