travis:
  secure:
    BINSTAR_TOKEN: Wdr3894vWa7VjPlXvvgRAdHnHUEbPaZp6nbayp/i1E1PhPB5nx2XDoPxoBYxinLSiYrW1bLKZRmR3TUBixaI/BR5SzwjDBL5vlKVKZqz/FKijObWefEdFD2e8THoLfF6xrl2ZDaTS2RT/s5dS3chUXuZmADLB8hDpZ7R/ZekhGftU6gwS9xU2ehHoEooGLB1LtJLWHYo42SWIT1PhXGQJXpaUnZFyqaLi3hxWN1/M5bMNrUsQMCpv9PtySrOyLpFY6wBCW8qA4xwclbWBYxG0fr+5sT7oaT23xo9zIaUSdU562cnW6nRv7dU4MtkIOAA2R3miFpVCc1NQ4o1IsWUxfTCIL5HFVpMIY8H/Gd6+Vm76KdldeQnBOmZLBpf3G9/RUQns82UFcxnlZ6Qp6bA2FcvffgqZZum79Io4LD2VqtAn3rQufX/gvbg6hOZQYuse5jsfUfLL1XuGBFDUBydeQztx/4Soy8ZoGC/GXtVWkIG1LuUdiFzj33VQh4SqHGQD5OE2CqOvGXFyu4YhFE3Al31xqLu/hajeJP0NzfHN4Yu7mJyzei7q+QRhs+8zMlhXb8qHNT1wP8/GYjj/mBdEXD3OkI6UE5WL0rKC8qvmkDtVZ3X0yN75AXC/ESCYThNLhQ4Sa4t7QDMl3CMV/5IvcoMRjLhvxRBbhE1hyVSM2k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
